include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for cup_off_coffee
LUCI_DEPENDS:=+cup_off_coffee +luci-base +rpcd-mod-file
LUCI_PKGARCH:=all
PKG_VERSION:=1.1.0
PKG_RELEASE:=4

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
